version: "3"
services:
  mysqldb:
    image: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opentrivia_db
  opentrivia:
    build: .
    environment:
      DB_HOST: mysqldb
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: opentrivia_db
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"

volumes:
  mysql_volume: {}